### ISSUE TITLE
I got this error cannot load such file -- active_job/railtie

### ISSUE THREAD

**Issue by ccfiel** [sprangular/sprangular#187]
Hello @joshnuss!

I did a fresh install using this steps
1. gem install sprangular_cli
2. sprangular install testni
3. cd testni
4. rails server

I got this error 
```
/home/chris/testni/config/application.rb:6:in `require': cannot load such file -- active_job/railtie (LoadError)
	from /home/chris/testni/config/application.rb:6:in `<top (required)>'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
When I open application.rb I found this line.

```
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"
# require "rails/test_unit/railtie"
```
In the comment it says "Pick the frameworks you want" what will I pick?

**Comment by ccfiel** [comment]
I tried to comment the line require "active_job/railtie". Am I doing it right? but when comment the line I got new error.

```
/home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ngannotate-rails-1.0.2/lib/ngannotate/rails/railtie.rb:2:in `<top (required)>': undefined method `sprockets_v3?' for Ngannotate:Module (NoMethodError)
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ngannotate-rails-1.0.2/lib/ngannotate/rails.rb:2:in `<top (required)>'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sprangular-0.1.0/lib/sprangular.rb:9:in `<top (required)>'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `each'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `block in require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `each'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib/bundler.rb:134:in `require'
	from /home/chris/testni/config/application.rb:16:in `<top (required)>'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
Any ideas?

**Comment by joshnuss** [comment]
Looks like the version of rails you are using is the problem, try 4.1.x (instead of 4.2.x)

**Comment by ccfiel** [comment]
Hi @joshnuss 

I used 4.1.8 this is my gemfile

```
source 'https://rails-assets.org'
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


gem 'spree_core', '2.4'
gem 'spree_api', '2.4'
gem 'spree_backend', '2.4'
gem 'spree_sample', '2.4'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'sprangular', '0.1.0'

```

this is my gemfile.lock

```
GIT
  remote: git://github.com/spree/spree_auth_devise.git
  revision: c53ccc17323e2c22e4b4fdf0292972ff44790233
  branch: 2-4-stable
  specs:
    spree_auth_devise (2.4.0)
      devise (~> 3.2.3)
      devise-encryptable (= 0.1.2)
      json
      multi_json
      spree_core (~> 2.4.0)

GIT
  remote: git://github.com/spree/spree_gateway.git
  revision: 3b40ced38a7643be6a83a9ee1901066e5d765e6c
  branch: 2-4-stable
  specs:
    spree_gateway (2.4.0)
      spree_core (~> 2.4.0)

GEM
  remote: https://rails-assets.org/
  remote: https://rubygems.org/
  specs:
    actionmailer (4.1.8)
      actionpack (= 4.1.8)
      actionview (= 4.1.8)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.8)
      actionview (= 4.1.8)
      activesupport (= 4.1.8)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.8)
      activesupport (= 4.1.8)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    active_model_serializers (0.8.3)
      activemodel (>= 3.0)
    active_utils (2.2.3)
      activesupport (>= 2.3.11)
      i18n
    activemerchant (1.44.1)
      active_utils (~> 2.2.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      json (~> 1.7)
      nokogiri (~> 1.4)
      offsite_payments (~> 2.0.0)
    activemodel (4.1.8)
      activesupport (= 4.1.8)
      builder (~> 3.1)
    activerecord (4.1.8)
      activemodel (= 4.1.8)
      activesupport (= 4.1.8)
      arel (~> 5.0.0)
    activesupport (4.1.8)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    acts_as_list (0.3.0)
      activerecord (>= 3.0)
    addressable (2.3.8)
    arel (5.0.1.20140414130214)
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (5.0.0)
      columnize (= 0.9.0)
    camertron-eprun (1.1.0)
    cancancan (1.9.2)
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    cldr-plurals-runtime-rb (1.0.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorize (0.7.7)
    columnize (0.9.0)
    css_parser (1.3.6)
      addressable
    debug_inspector (0.0.2)
    deface (1.0.1)
      colorize (>= 0.5.8)
      nokogiri (~> 1.6.0)
      polyglot
      rails (>= 3.1)
    devise (3.2.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    erubis (2.7.0)
    execjs (2.5.2)
    ffaker (1.32.1)
    font-awesome-rails (4.3.0.0)
      railties (>= 3.2, < 5.0)
    friendly_id (5.0.5)
      activerecord (>= 4.0.0)
    geocoder (1.2.9)
    highline (1.6.21)
    htmlentities (4.3.3)
    httparty (0.13.5)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    jbuilder (2.3.0)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.3)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitest (5.7.0)
    monetize (1.3.0)
      money (~> 6.5.0)
    money (6.5.1)
      i18n (>= 0.6.4, <= 0.7.0)
    multi_json (1.11.1)
    multi_xml (0.5.5)
    ngannotate-rails (1.0.2)
      execjs
      rails (>= 3.1)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    offsite_payments (2.0.1)
      active_utils (~> 2.2.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (~> 0.5)
      json (~> 1.7)
      money (< 7.0.0)
      nokogiri (~> 1.4)
    orm_adapter (0.5.0)
    paperclip (4.2.4)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
    paranoia (2.1.3)
      activerecord (~> 4.0)
    polyamorous (1.2.0)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    premailer (1.8.4)
      css_parser (>= 1.3.6)
      htmlentities (>= 4.0.0)
    premailer-rails (1.8.2)
      actionmailer (>= 3, < 5)
      premailer (~> 1.7, >= 1.7.9)
    prerender_rails (1.1.2)
      activesupport
      rack
    rabl (0.9.4.pre1)
      activesupport (>= 2.3.14)
    rack (1.5.5)
    rack-rewrite (1.5.1)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.8)
      actionmailer (= 4.1.8)
      actionpack (= 4.1.8)
      actionview (= 4.1.8)
      activemodel (= 4.1.8)
      activerecord (= 4.1.8)
      activesupport (= 4.1.8)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.8)
      sprockets-rails (~> 2.0)
    rails-assets-angular (1.3.9)
    rails-assets-angular-animate (1.3.9)
      rails-assets-angular (= 1.3.9)
    rails-assets-angular-i18n (1.4.1)
    rails-assets-angular-motion (0.4.2)
    rails-assets-angular-route (1.3.9)
      rails-assets-angular (= 1.3.9)
    rails-assets-angular-sanitize (1.3.9)
      rails-assets-angular (= 1.3.9)
    rails-assets-angular-strap (2.2.4)
      rails-assets-angular (>= 1.2.21, < 2)
    rails-assets-angular-translate (2.7.2)
      rails-assets-angular (>= 1.2.26, <= 1.5)
    rails-assets-angularytics (0.4.0)
      rails-assets-angular
    rails-assets-bootstrap-additions (0.3.1)
    rails-assets-bootstrap-sass-official (3.3.5)
      rails-assets-jquery (>= 1.9.0)
    rails-assets-jasmine (2.0.4)
    rails-assets-jasmine-sinon (0.4.0)
      rails-assets-jasmine (~> 2.0.0)
      rails-assets-sinonjs (>= 1.7.1)
    rails-assets-jquery (2.1.4)
    rails-assets-sinon (1.15.3)
    rails-assets-sinonjs (1.14.1)
    rails-assets-underscore (1.8.3)
    rails-assets-underscore.string (3.1.1)
    railties (4.1.8)
      actionpack (= 4.1.8)
      activesupport (= 4.1.8)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rdoc (4.2.0)
    sass (3.4.15)
    sass-rails (5.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    select2-rails (3.5.9.3)
      thor (~> 0.14)
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slim-rails (3.0.1)
      actionmailer (>= 3.1, < 5.0)
      actionpack (>= 3.1, < 5.0)
      activesupport (>= 3.1, < 5.0)
      railties (>= 3.1, < 5.0)
      slim (~> 3.0)
    sprangular (0.1.0)
      active_model_serializers (~> 0.8.3)
      coffee-rails
      font-awesome-rails (~> 4.2)
      geocoder
      jquery-rails
      ngannotate-rails
      prerender_rails
      rack-rewrite
      rails
      rails-assets-angular (= 1.3.9)
      rails-assets-angular-animate
      rails-assets-angular-i18n
      rails-assets-angular-motion
      rails-assets-angular-route
      rails-assets-angular-sanitize
      rails-assets-angular-strap
      rails-assets-angular-translate
      rails-assets-angularytics
      rails-assets-bootstrap-additions
      rails-assets-bootstrap-sass-official
      rails-assets-jasmine-sinon
      rails-assets-sinon
      rails-assets-underscore
      rails-assets-underscore.string
      sass-rails
      slim-rails
      spree_api (>= 2.4)
      spree_auth_devise
      spree_core (>= 2.4)
    spree_api (2.4.0)
      rabl (~> 0.9.4.pre1)
      spree_core (= 2.4.0)
      versioncake (~> 2.3.1)
    spree_backend (2.4.0)
      jquery-rails (~> 3.1.2)
      jquery-ui-rails (~> 5.0.0)
      select2-rails (~> 3.5.0)
      spree_api (= 2.4.0)
      spree_core (= 2.4.0)
    spree_core (2.4.0)
      activemerchant (~> 1.44.1)
      acts_as_list (= 0.3.0)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.9.2)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 1.16)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.0.4)
      highline (~> 1.6.18)
      httparty (~> 0.11)
      json (~> 1.7)
      kaminari (~> 0.15, >= 0.15.1)
      monetize
      paperclip (~> 4.2.0)
      paranoia (~> 2.0)
      premailer-rails
      rails (~> 4.1.8)
      ransack (~> 1.4.1)
      state_machine (= 1.2.0)
      stringex (~> 1.5.1)
      truncate_html (= 0.9.2)
      twitter_cldr (~> 3.0)
    spree_sample (2.4.0)
      spree_core (= 2.4.0)
    spring (1.3.6)
    sprockets (3.2.0)
      rack (~> 1.0)
    sprockets-rails (2.3.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.10)
    state_machine (1.2.0)
    stringex (1.5.1)
    temple (0.7.6)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    truncate_html (0.9.2)
    turbolinks (2.5.3)
      coffee-rails
    twitter_cldr (3.2.1)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0.0)
      json
      tzinfo
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.1.3)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.1.0)
  jbuilder (~> 2.0)
  jquery-rails
  rails (= 4.1.8)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  sprangular (= 0.1.0)
  spree_api (= 2.4)
  spree_auth_devise!
  spree_backend (= 2.4)
  spree_core (= 2.4)
  spree_gateway!
  spree_sample (= 2.4)
  spring
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.10.3
```

**Comment by joshnuss** [comment]
ActiveJob is a feature in 4.2.x so something must be setup wrong. Could be that sprangular_cli used the wrong rails version to create your app.

**Comment by joshnuss** [comment]
For now, you might want to remove 4.2.x from your system and re-run sprangular-cli `gem uninstall rails -v 4.2.#`

**Comment by ccfiel** [comment]
@joshnuss thanks!

**Comment by dorin2002** [comment]
Hello. when i meet command "ruby inline.rb" i see this issue:
![1513788004163](https://user-images.githubusercontent.com/22981368/34217835-3a22f484-e5b5-11e7-81a3-370460eaad1c.jpg)

**Comment by dorin2002** [comment]
does anyone know why?
